/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1SlideBots200,
  GetApiV1SlideBotsParams,
  PostApiV1SlideBots200,
  PostApiV1SlideBotsBody,
  Request,
  Response
} from '.././model';

import { customAxiosFunction } from '../../lib/axios';




export const postApiV1SlideBotsIdExecute = (
    id: string,
    request: Request,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<Response>(
      {url: `/api/v1/slide-bots/${id}/execute`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: request, signal
    },
      );
    }
  


export const getPostApiV1SlideBotsIdExecuteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>, TError,{id: string;data: Request}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>, TError,{id: string;data: Request}, TContext> => {

const mutationKey = ['postApiV1SlideBotsIdExecute'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>, {id: string;data: Request}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SlideBotsIdExecute(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SlideBotsIdExecuteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>>
    export type PostApiV1SlideBotsIdExecuteMutationBody = Request
    export type PostApiV1SlideBotsIdExecuteMutationError = void

    export const usePostApiV1SlideBotsIdExecute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>, TError,{id: string;data: Request}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SlideBotsIdExecute>>,
        TError,
        {id: string;data: Request},
        TContext
      > => {

      const mutationOptions = getPostApiV1SlideBotsIdExecuteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const getApiV1SlideBots = (
    params?: GetApiV1SlideBotsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<GetApiV1SlideBots200>(
      {url: `/api/v1/slide-bots`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetApiV1SlideBotsQueryKey = (params?: GetApiV1SlideBotsParams,) => {
    return [`/api/v1/slide-bots`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1SlideBotsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SlideBots>>, TError = unknown>(params?: GetApiV1SlideBotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SlideBotsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SlideBots>>> = ({ signal }) => getApiV1SlideBots(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SlideBotsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SlideBots>>>
export type GetApiV1SlideBotsQueryError = unknown


export function useGetApiV1SlideBots<TData = Awaited<ReturnType<typeof getApiV1SlideBots>>, TError = unknown>(
 params: undefined |  GetApiV1SlideBotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SlideBots>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SlideBots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SlideBots<TData = Awaited<ReturnType<typeof getApiV1SlideBots>>, TError = unknown>(
 params?: GetApiV1SlideBotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SlideBots>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SlideBots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SlideBots<TData = Awaited<ReturnType<typeof getApiV1SlideBots>>, TError = unknown>(
 params?: GetApiV1SlideBotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SlideBots<TData = Awaited<ReturnType<typeof getApiV1SlideBots>>, TError = unknown>(
 params?: GetApiV1SlideBotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SlideBots>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SlideBotsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const postApiV1SlideBots = (
    postApiV1SlideBotsBody: PostApiV1SlideBotsBody,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<PostApiV1SlideBots200>(
      {url: `/api/v1/slide-bots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1SlideBotsBody, signal
    },
      );
    }
  


export const getPostApiV1SlideBotsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBots>>, TError,{data: PostApiV1SlideBotsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBots>>, TError,{data: PostApiV1SlideBotsBody}, TContext> => {

const mutationKey = ['postApiV1SlideBots'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SlideBots>>, {data: PostApiV1SlideBotsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SlideBots(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SlideBotsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SlideBots>>>
    export type PostApiV1SlideBotsMutationBody = PostApiV1SlideBotsBody
    export type PostApiV1SlideBotsMutationError = unknown

    export const usePostApiV1SlideBots = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SlideBots>>, TError,{data: PostApiV1SlideBotsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SlideBots>>,
        TError,
        {data: PostApiV1SlideBotsBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1SlideBotsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    