/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateProfileRequest,
  CreateProfileResponse,
  OpenProfileRequest,
  OpenProfileResponse,
  ProfileListData,
  ProfileListRequest
} from '.././model';

import { customAxiosFunction } from '../../lib/axios';




export const postApiV1BrowserProfilesCreate = (
    createProfileRequest: CreateProfileRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<CreateProfileResponse>(
      {url: `/api/v1/browser-profiles/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProfileRequest, signal
    },
      );
    }
  


export const getPostApiV1BrowserProfilesCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>, TError,{data: CreateProfileRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>, TError,{data: CreateProfileRequest}, TContext> => {

const mutationKey = ['postApiV1BrowserProfilesCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>, {data: CreateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BrowserProfilesCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BrowserProfilesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>>
    export type PostApiV1BrowserProfilesCreateMutationBody = CreateProfileRequest
    export type PostApiV1BrowserProfilesCreateMutationError = void

    export const usePostApiV1BrowserProfilesCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>, TError,{data: CreateProfileRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BrowserProfilesCreate>>,
        TError,
        {data: CreateProfileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1BrowserProfilesCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const postApiV1BrowserProfilesList = (
    profileListRequest: ProfileListRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<ProfileListData>(
      {url: `/api/v1/browser-profiles/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: profileListRequest, signal
    },
      );
    }
  


export const getPostApiV1BrowserProfilesListMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>, TError,{data: ProfileListRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>, TError,{data: ProfileListRequest}, TContext> => {

const mutationKey = ['postApiV1BrowserProfilesList'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>, {data: ProfileListRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BrowserProfilesList(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BrowserProfilesListMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>>
    export type PostApiV1BrowserProfilesListMutationBody = ProfileListRequest
    export type PostApiV1BrowserProfilesListMutationError = void

    export const usePostApiV1BrowserProfilesList = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>, TError,{data: ProfileListRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BrowserProfilesList>>,
        TError,
        {data: ProfileListRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1BrowserProfilesListMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const postApiV1BrowserProfilesOpen = (
    openProfileRequest: OpenProfileRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<OpenProfileResponse>(
      {url: `/api/v1/browser-profiles/open`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: openProfileRequest, signal
    },
      );
    }
  


export const getPostApiV1BrowserProfilesOpenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>, TError,{data: OpenProfileRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>, TError,{data: OpenProfileRequest}, TContext> => {

const mutationKey = ['postApiV1BrowserProfilesOpen'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>, {data: OpenProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BrowserProfilesOpen(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BrowserProfilesOpenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>>
    export type PostApiV1BrowserProfilesOpenMutationBody = OpenProfileRequest
    export type PostApiV1BrowserProfilesOpenMutationError = void

    export const usePostApiV1BrowserProfilesOpen = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>, TError,{data: OpenProfileRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BrowserProfilesOpen>>,
        TError,
        {data: OpenProfileRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1BrowserProfilesOpenMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    