/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { _ } from './_';

export interface ContainerConfiguration2 {
  id?: string;
  routePrefix?: string;
  /** @nullable */
  defaultPageSize?: number | null;
  endpoints?: _;
}
