/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Endpoint } from './endpoint';

export interface ContainerConfiguration {
  id?: string;
  routePrefix?: string;
  /** @nullable */
  defaultPageSize?: number | null;
  /** @nullable */
  endpoints?: Endpoint[] | null;
}
