/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProxyConfig } from './proxyConfig';

export interface CreateProfileRequest {
  /** @nullable */
  siteId?: number | null;
  siteUrl?: string;
  /** @nullable */
  color?: string | null;
  name?: string;
  /** @nullable */
  note?: string | null;
  groupId?: number;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  tfaSecret?: string | null;
  /** @nullable */
  cookie?: string | null;
  proxyConfig?: ProxyConfig;
}
