/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProxyConfig } from './proxyConfig';

/**
 * @nullable
 */
export type CreateProfileRequest = {
  site_id?: number;
  site_url?: string;
  color?: string;
  name?: string;
  /** @nullable */
  note?: string | null;
  group_id?: number;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  tfa_secret?: string | null;
  /** @nullable */
  cookie?: string | null;
  proxy_config?: ProxyConfig;
} | null;
