/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProfileError } from './createProfileError';

export interface CreateProfileResponse {
  error?: CreateProfileError;
  data?: number;
}
