/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MSSQLConfig } from './mSSQLConfig';
import type { PostgreSQLConfig } from './postgreSQLConfig';
import type { MySQLConfig } from './mySQLConfig';
import type { OracleConfig } from './oracleConfig';

export interface DatabaseConfiguration {
  mssql?: MSSQLConfig;
  postgreSQL?: PostgreSQLConfig;
  mySQL?: MySQLConfig;
  oracle?: OracleConfig;
}
