/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type EndpointODataSupportOptions = {
  id?: string;
  /** @nullable */
  maxTop?: number | null;
  allowFilter?: boolean;
  allowOrderBy?: boolean;
} | null;
