/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HttpMethod } from './httpMethod';
import type { EndpointAuthorization } from './endpointAuthorization';
import type { EndpointODataSupportOptions } from './endpointODataSupportOptions';
import type { RuntimeEntityDefinition } from './runtimeEntityDefinition';
import type { ContainerConfiguration4 } from './containerConfiguration4';

export interface Endpoint2 {
  id?: string;
  path?: string;
  method?: HttpMethod;
  /** @nullable */
  description?: string | null;
  isAuthenticationRequired?: boolean;
  authorization?: EndpointAuthorization;
  oDataOptions?: EndpointODataSupportOptions;
  runtimeEntityDefinition?: RuntimeEntityDefinition;
  containerConfiguration?: ContainerConfiguration4;
}
