/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type EndpointAuthorization = {
  id?: string;
  /** @nullable */
  roles?: string | null;
  /** @nullable */
  permissions?: string | null;
  /** @nullable */
  policies?: string | null;
} | null;
