/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiV1SlideBots200ValueStatus = typeof GetApiV1SlideBots200ValueStatus[keyof typeof GetApiV1SlideBots200ValueStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1SlideBots200ValueStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
