/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1TenantsParams = {
/**
 * Filter the results using OData syntax.
 */
$filter?: string;
/**
 * Specify the number of records to return.
 */
$top?: number;
/**
 * Specify the number of records to skip.
 */
$skip?: number;
/**
 * Specify the order of results.
 */
$orderby?: string;
/**
 * Expand related entities.
 */
$expand?: string;
/**
 * Specify the fields to return.
 */
$select?: string;
/**
 * Include the count of the total matching entities.
 */
$count?: boolean;
};
