/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1TenantsKey200Value } from './getApiV1TenantsKey200Value';

export type GetApiV1TenantsKey200 = {
  value?: GetApiV1TenantsKey200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
