/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1SlideBots200Value } from './getApiV1SlideBots200Value';

export type GetApiV1SlideBots200 = {
  value?: GetApiV1SlideBots200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
