/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Tenants200ValuePoliciesItem } from './getApiV1Tenants200ValuePoliciesItem';
import type { GetApiV1Tenants200ValueRolesItem } from './getApiV1Tenants200ValueRolesItem';
import type { GetApiV1Tenants200ValueTenantUsersItem } from './getApiV1Tenants200ValueTenantUsersItem';

export type GetApiV1Tenants200Value = {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  policies?: GetApiV1Tenants200ValuePoliciesItem[] | null;
  /** @nullable */
  roles?: GetApiV1Tenants200ValueRolesItem[] | null;
  /** @nullable */
  tenantUsers?: GetApiV1Tenants200ValueTenantUsersItem[] | null;
};
