/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1Tenants200ValuePoliciesItem = {
  id: string;
  /** @nullable */
  description?: string | null;
  name: string;
  tenantId: string;
};
