/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Tenants200Value } from './getApiV1Tenants200Value';

export type GetApiV1Tenants200 = {
  value?: GetApiV1Tenants200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
