/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1TenantsKey200ValuePoliciesItem } from './getApiV1TenantsKey200ValuePoliciesItem';
import type { GetApiV1TenantsKey200ValueRolesItem } from './getApiV1TenantsKey200ValueRolesItem';
import type { GetApiV1TenantsKey200ValueTenantUsersItem } from './getApiV1TenantsKey200ValueTenantUsersItem';

export type GetApiV1TenantsKey200Value = {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  policies?: GetApiV1TenantsKey200ValuePoliciesItem[] | null;
  /** @nullable */
  roles?: GetApiV1TenantsKey200ValueRolesItem[] | null;
  /** @nullable */
  tenantUsers?: GetApiV1TenantsKey200ValueTenantUsersItem[] | null;
};
