/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type MapIdentityApiConfirmEmailParams = {
userId: string;
code: string;
changedEmail?: string;
};
