/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MSSQLConfig = {
  server: string;
  /** @nullable */
  port?: number | null;
  database: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  integratedSecurity?: boolean;
  encrypt?: boolean;
  trustServerCertificate?: boolean;
  multipleActiveResultSets?: boolean;
  /** @nullable */
  connectionTimeout?: number | null;
  /** @nullable */
  commandTimeout?: number | null;
} | null;
