/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MySQLConfig = {
  host: string;
  /** @nullable */
  port?: number | null;
  database: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  charset?: string | null;
  sslMode?: boolean;
  /** @nullable */
  connectionTimeout?: number | null;
  /** @nullable */
  commandTimeout?: number | null;
} | null;
