/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OpenProfileError } from './openProfileError';
import type { OpenProfileData } from './openProfileData';

export interface OpenProfileResponse {
  error?: OpenProfileError;
  data?: OpenProfileData;
}
