/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type OpenProfileData = {
  debuggingAddress?: string;
  debuggingPort?: number;
  profileId?: number;
  pid?: number;
  ws?: string;
  gateway?: string;
  webdriver?: string;
} | null;
