/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OpenProfileRequest {
  profileId?: number;
  /** @nullable */
  args?: string[] | null;
  /** @nullable */
  loadExtensions?: boolean | null;
  /** @nullable */
  loadProfileInfoPage?: boolean | null;
  /** @nullable */
  cookiesBackup?: boolean | null;
  /** @nullable */
  cookie?: string | null;
}
