/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OracleConnectionType } from './oracleConnectionType';

/**
 * @nullable
 */
export type OracleConfig = {
  host: string;
  /** @nullable */
  port?: number | null;
  serviceName: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  connectionType?: OracleConnectionType;
  /** @nullable */
  connectionTimeout?: number | null;
  /** @nullable */
  commandTimeout?: number | null;
} | null;
