/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type OracleConnectionType = typeof OracleConnectionType[keyof typeof OracleConnectionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OracleConnectionType = {
  Basic: 'Basic',
  TNS: 'TNS',
} as const;
