/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiV1TenantsKeyBodyRolesItem = {
  id: string;
  /** @nullable */
  concurrencyStamp?: string | null;
  description: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  normalizedName?: string | null;
  tenantId: string;
};
