/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1TenantsKey200Value } from './patchApiV1TenantsKey200Value';

export type PatchApiV1TenantsKey200 = {
  value?: PatchApiV1TenantsKey200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
