/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1TenantsKey200ValuePoliciesItem } from './patchApiV1TenantsKey200ValuePoliciesItem';
import type { PatchApiV1TenantsKey200ValueRolesItem } from './patchApiV1TenantsKey200ValueRolesItem';
import type { PatchApiV1TenantsKey200ValueTenantUsersItem } from './patchApiV1TenantsKey200ValueTenantUsersItem';

export type PatchApiV1TenantsKey200Value = {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  policies?: PatchApiV1TenantsKey200ValuePoliciesItem[] | null;
  /** @nullable */
  roles?: PatchApiV1TenantsKey200ValueRolesItem[] | null;
  /** @nullable */
  tenantUsers?: PatchApiV1TenantsKey200ValueTenantUsersItem[] | null;
};
