/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiV1TenantsKey200ValueTenantUsersItem = {
  userId: string;
  tenantId: string;
  createdAt: string;
  isOwner: boolean;
  /** @nullable */
  roleId?: string | null;
};
