/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1TenantsKeyBodyPoliciesItem } from './patchApiV1TenantsKeyBodyPoliciesItem';
import type { PatchApiV1TenantsKeyBodyRolesItem } from './patchApiV1TenantsKeyBodyRolesItem';
import type { PatchApiV1TenantsKeyBodyTenantUsersItem } from './patchApiV1TenantsKeyBodyTenantUsersItem';

export type PatchApiV1TenantsKeyBody = {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  policies?: PatchApiV1TenantsKeyBodyPoliciesItem[] | null;
  /** @nullable */
  roles?: PatchApiV1TenantsKeyBodyRolesItem[] | null;
  /** @nullable */
  tenantUsers?: PatchApiV1TenantsKeyBodyTenantUsersItem[] | null;
};
