/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1SlideBots200ValueLastDuration } from './postApiV1SlideBots200ValueLastDuration';
import type { PostApiV1SlideBots200ValueStatus } from './postApiV1SlideBots200ValueStatus';

export type PostApiV1SlideBots200Value = {
  /** @nullable */
  id?: string | null;
  browserProfileId: string;
  description: string;
  /** @nullable */
  isActive?: boolean | null;
  lastDuration: PostApiV1SlideBots200ValueLastDuration;
  lastRunAt: string;
  logs: string;
  /** @nullable */
  name?: string | null;
  outputPath: string;
  /** @nullable */
  status?: PostApiV1SlideBots200ValueStatus;
  /** @nullable */
  steps?: string | null;
};
