/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostgreSQLSslMode } from './postgreSQLSslMode';

/**
 * @nullable
 */
export type PostgreSQLConfig = {
  host: string;
  /** @nullable */
  port?: number | null;
  database: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  schema?: string | null;
  sslMode?: PostgreSQLSslMode;
  /** @nullable */
  connectionTimeout?: number | null;
  /** @nullable */
  commandTimeout?: number | null;
} | null;
