/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Tenants200Value } from './postApiV1Tenants200Value';

export type PostApiV1Tenants200 = {
  value?: PostApiV1Tenants200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
