/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PostApiV1SlideBotsBodyStatus = typeof PostApiV1SlideBotsBodyStatus[keyof typeof PostApiV1SlideBotsBodyStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiV1SlideBotsBodyStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
