/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1SlideBots200Value } from './postApiV1SlideBots200Value';

export type PostApiV1SlideBots200 = {
  value?: PostApiV1SlideBots200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
