/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1SlideBotsBodyLastDuration } from './postApiV1SlideBotsBodyLastDuration';
import type { PostApiV1SlideBotsBodyStatus } from './postApiV1SlideBotsBodyStatus';

export type PostApiV1SlideBotsBody = {
  /** @nullable */
  id?: string | null;
  browserProfileId: string;
  description: string;
  /** @nullable */
  isActive?: boolean | null;
  lastDuration: PostApiV1SlideBotsBodyLastDuration;
  lastRunAt: string;
  logs: string;
  /** @nullable */
  name?: string | null;
  outputPath: string;
  /** @nullable */
  status?: PostApiV1SlideBotsBodyStatus;
  /** @nullable */
  steps?: string | null;
};
