/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export type PostgreSQLSslMode = typeof PostgreSQLSslMode[keyof typeof PostgreSQLSslMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgreSQLSslMode = {
  Disable: 'Disable',
  Require: 'Require',
  VerifyCA: 'VerifyCA',
  VerifyFull: 'VerifyFull',
} as const;
