/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ProfileInfo {
  profileId?: number;
  /** @nullable */
  siteUrl?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  lastOpenTime?: number;
  groupId?: number;
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  tagId?: string | null;
  /** @nullable */
  tagName?: string | null;
  proxyMode?: number;
  /** @nullable */
  proxyId?: number | null;
  /** @nullable */
  proxyType?: string | null;
  /** @nullable */
  proxyIp?: string | null;
  /** @nullable */
  proxyPort?: string | null;
  /** @nullable */
  realIp?: string | null;
  /** @nullable */
  cachePath?: string | null;
}
