/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ProfileListRequest = {
  /** @nullable */
  profileId?: number | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  groupId?: number | null;
  /** @nullable */
  tagId?: number | null;
  page?: number;
  limit?: number;
} | null;
