/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProxyConfigProxyDataJsonFormat } from './proxyConfigProxyDataJsonFormat';

/**
 * @nullable
 */
export type ProxyConfig = {
  proxy_mode?: number;
  proxy_check_line?: string;
  /** @nullable */
  proxy_id?: string | null;
  proxy_type?: string;
  /** @nullable */
  proxy_ip?: string | null;
  /** @nullable */
  proxy_port?: string | null;
  /** @nullable */
  proxy_user?: string | null;
  /** @nullable */
  proxy_password?: string | null;
  ip_detection?: string;
  traffic_package_ip_policy?: boolean;
  proxy_service?: string;
  proxy_data_format_type?: string;
  proxy_data_txt_format?: string;
  proxy_data_json_format?: ProxyConfigProxyDataJsonFormat;
  proxy_extraction_method?: string;
  /** @nullable */
  proxy_url?: string | null;
  use_system_proxy?: string;
  enable_bypass?: string;
  /** @nullable */
  bypass_list?: string | null;
} | null;
