/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProxyConfigProxyDataJsonFormat } from './proxyConfigProxyDataJsonFormat';

/**
 * @nullable
 */
export type ProxyConfig = {
  proxyMode?: number;
  proxyCheckLine?: string;
  /** @nullable */
  proxyId?: string | null;
  proxyType?: string;
  /** @nullable */
  proxyIp?: string | null;
  /** @nullable */
  proxyPort?: string | null;
  /** @nullable */
  proxyUser?: string | null;
  /** @nullable */
  proxyPassword?: string | null;
  ipDetection?: string;
  trafficPackageIpPolicy?: boolean;
  proxyService?: string;
  proxyDataFormatType?: string;
  proxyDataTxtFormat?: string;
  proxyDataJsonFormat?: ProxyConfigProxyDataJsonFormat;
  proxy_extraction_method?: string;
  /** @nullable */
  proxy_url?: string | null;
  use_system_proxy?: string;
  enable_bypass?: string;
  /** @nullable */
  bypass_list?: string | null;
} | null;
