/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV1TenantsKey200Value } from './putApiV1TenantsKey200Value';

export type PutApiV1TenantsKey200 = {
  value?: PutApiV1TenantsKey200Value;
  /** @nullable */
  '@odata.count'?: number | null;
};
