/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DatabaseConfiguration } from './databaseConfiguration';
import type { DatabaseProvider } from './databaseProvider';

export interface Request2 {
  databaseConfiguration?: DatabaseConfiguration;
  databaseProvider?: DatabaseProvider;
}
