/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Response {
  /** @nullable */
  outputPath?: string | null;
  /** @nullable */
  logs?: string | null;
}
