/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RelationshipType } from './relationshipType';

export interface RuntimeEntityRelationshipDefinition {
  id?: string;
  name?: string;
  targetEntity?: string;
  targetProperty?: string;
  type?: RelationshipType;
}
