/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RuntimeEntityPropertyDefinition } from './runtimeEntityPropertyDefinition';
import type { RuntimeEntityRelationshipDefinition } from './runtimeEntityRelationshipDefinition';

/**
 * @nullable
 */
export type RuntimeEntityDefinition = {
  id?: string;
  namespace: string;
  name: string;
  properties?: RuntimeEntityPropertyDefinition[];
  relationships?: RuntimeEntityRelationshipDefinition[];
} | null;
