/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Request2,
  Response2
} from '.././model';

import { customAxiosFunction } from '../../lib/axios';




export const postApiV1DatabasesTablesDatabasesTables = (
    request2: Request2,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<Response2>(
      {url: `/api/v1/databases/tables/databases/tables`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: request2, signal
    },
      );
    }
  


export const getPostApiV1DatabasesTablesDatabasesTablesMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>, TError,{data: Request2}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>, TError,{data: Request2}, TContext> => {

const mutationKey = ['postApiV1DatabasesTablesDatabasesTables'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>, {data: Request2}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1DatabasesTablesDatabasesTables(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1DatabasesTablesDatabasesTablesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>>
    export type PostApiV1DatabasesTablesDatabasesTablesMutationBody = Request2
    export type PostApiV1DatabasesTablesDatabasesTablesMutationError = void

    export const usePostApiV1DatabasesTablesDatabasesTables = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>, TError,{data: Request2}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1DatabasesTablesDatabasesTables>>,
        TError,
        {data: Request2},
        TContext
      > => {

      const mutationOptions = getPostApiV1DatabasesTablesDatabasesTablesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    