/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ContainerConfiguration,
  ContainerConfiguration3
} from '.././model';

import { customAxiosFunction } from '../../lib/axios';




export const postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations = (
    containerConfiguration3: ContainerConfiguration3,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<ContainerConfiguration>(
      {url: `/api/v1/endpoints/container-configurations/endpoints/container-configurations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: containerConfiguration3, signal
    },
      );
    }
  


export const getPostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurationsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>, TError,{data: ContainerConfiguration3}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>, TError,{data: ContainerConfiguration3}, TContext> => {

const mutationKey = ['postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>, {data: ContainerConfiguration3}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>>
    export type PostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurationsMutationBody = ContainerConfiguration3
    export type PostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurationsMutationError = void

    export const usePostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>, TError,{data: ContainerConfiguration3}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurations>>,
        TError,
        {data: ContainerConfiguration3},
        TContext
      > => {

      const mutationOptions = getPostApiV1EndpointsContainerConfigurationsEndpointsContainerConfigurationsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    