/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CFW.AppHost | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Endpoint2
} from '.././model';

import { customAxiosFunction } from '../../lib/axios';




export const postApiV1EndpointsEndpoints = (
    endpoint2: Endpoint2,
 signal?: AbortSignal
) => {
      
      
      return customAxiosFunction<Endpoint2>(
      {url: `/api/v1/endpoints/endpoints`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: endpoint2, signal
    },
      );
    }
  


export const getPostApiV1EndpointsEndpointsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>, TError,{data: Endpoint2}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>, TError,{data: Endpoint2}, TContext> => {

const mutationKey = ['postApiV1EndpointsEndpoints'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>, {data: Endpoint2}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1EndpointsEndpoints(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1EndpointsEndpointsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>>
    export type PostApiV1EndpointsEndpointsMutationBody = Endpoint2
    export type PostApiV1EndpointsEndpointsMutationError = void

    export const usePostApiV1EndpointsEndpoints = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>, TError,{data: Endpoint2}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1EndpointsEndpoints>>,
        TError,
        {data: Endpoint2},
        TContext
      > => {

      const mutationOptions = getPostApiV1EndpointsEndpointsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    